### ISSUE TITLE
Only github tokens generated by Franklin are valid for API calls

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin-api#56]

**Comment by oudeismetis** [comment]
2 checks could be done here. 1) On any API call, confirm that token is already in the DB. If it's not, reject request and "send them" in the direction of logging in again. 2) Accept any github oauth token as we do now, but do a check to make sure that token was issued by the Franklin application. 

Which of the two paths we pick above is largely dictated by how we handle expired oauth tokens. If we want to force all tokens to be issued by our auth/github/ endpoint, then option 1 is better.
