### ISSUE TITLE
Error 422 when re-adding deleted repo

### ISSUE THREAD

**Issue by camiriveron** [istrategylabs/franklin-api#69]
When you add a repo, then delete it and re-add it again, you get a 422 error from api: unprocessable entity, but the repo is actually re-added to franklin system.

**Comment by oudeismetis** [comment]
This is because the delete function currently only clears the DB. We need API to also make a call to github to remove the webhook we created.

The 422 error is coming from Github and means "The webhook you are trying to create already exists".

**Comment by oudeismetis** [comment]
Also, we'll want another story to have API kick off some sort of worker to go over to the file system and delete the project files. 

Was talking to Abrahams/Julian about this yesterday. It could be a lazy worker where we just through the task on a job queue to be run nightly. Might be a whole new project that sits next to builder as builder is also a utility that that operates on the file system and is kicked off by the API.
