### ISSUE TITLE
Parse franklin.yml and pass to builder

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin-api#94]

**Comment by oudeismetis** [comment]
Began working on this, but we are tabling this effort for now. Some notes:
- This should all happen inside of franklin-build as franklin-api does need or care about anything inside the .franklin.yml file and builder is already fetching the file when it clones.
- builder will have to change a little. Most likely, the cloning of the repo will happen outside of docker. After cloning, builder will process the .franklin.yml file so it can determine output folder, npm version, etc.
- Once build related matadata from the project has been ingested, builder will construct a customer dockerfile for that project that will likely inherit from base images for the node version, npm version, etc. 
- The dockerfile will be run by attaching to it the folder where github was cloned to.
- The output folder will of course no longer be hard coded.
- Most of the process will be as it is today with everything being cleaned up at the end.

This will likely mean that, for optimization purposes, we may want to keep the cloned repo around somewhere so the future builds will fetch less data from github. But that is a separate task/story.
